import type { Environment } from '../../src/config/env';

export const validEnvironmentInput: NodeJS.ProcessEnv = {
  NODE_ENV: 'test',
  PORT: '4000',
  LOG_LEVEL: 'silent',
  MONGODB_URI: 'mongodb://localhost:27017/sentinel',
  REDIS_URL: 'redis://localhost:6379',
  BULLMQ_PREFIX: 'sentinel',
  JWT_SECRET: 'a-test-secret-that-is-long-enough',
  JWT_EXPIRES_IN: '7d',
  CLIENT_ORIGIN: 'http://localhost:5173',
  ENABLED_REGIONS: 'mumbai,singapore,frankfurt',
  PROBE_REGION: 'mumbai',
  PROBE_CONCURRENCY: '20',
  SCHEDULER_POLL_INTERVAL_MS: '5000',
  GLOBAL_CHECK_TIMEOUT_MS: '10000',
  MAX_RESPONSE_BODY_BYTES: '65536',
  ALLOW_PRIVATE_NETWORK_TARGETS: 'false',
  AI_ENABLED: 'false',
  OPENAI_API_KEY: 'replace-with-provider-key',
  OPENAI_MODEL: 'replace-with-supported-model',
  AI_REQUEST_TIMEOUT_MS: '30000',
};

export const validEnvironment: Environment = {
  NODE_ENV: 'test',
  PORT: 4000,
  LOG_LEVEL: 'silent',
  MONGODB_URI: 'mongodb://localhost:27017/sentinel',
  REDIS_URL: 'redis://localhost:6379',
  BULLMQ_PREFIX: 'sentinel',
  JWT_SECRET: 'a-test-secret-that-is-long-enough',
  JWT_EXPIRES_IN: '7d',
  CLIENT_ORIGIN: 'http://localhost:5173',
  ENABLED_REGIONS: ['mumbai', 'singapore', 'frankfurt'],
  PROBE_REGION: 'mumbai',
  PROBE_CONCURRENCY: 20,
  SCHEDULER_POLL_INTERVAL_MS: 5000,
  GLOBAL_CHECK_TIMEOUT_MS: 10000,
  MAX_RESPONSE_BODY_BYTES: 65_536,
  ALLOW_PRIVATE_NETWORK_TARGETS: false,
  AI_ENABLED: false,
  OPENAI_API_KEY: 'replace-with-provider-key',
  OPENAI_MODEL: 'replace-with-supported-model',
  AI_REQUEST_TIMEOUT_MS: 30_000,
};
